"use client";

import { useEffect, useMemo, useState } from "react";
import { downloadReportExcel } from "@/lib/exportExcel";

type Appliance = {
  id?: string | number;
  name: string;
  watts: number;
  quantity: number;
  hoursPerDay: number;
  critical: boolean;
};

type SolarResults = {
  dailyEnergy: number;
  monthlyEnergy: number;
  peakLoad: number;
  criticalLoad: number;
  criticalEnergyPerHour: number;
  sunHours: number;
  panel: number;
  offset: number;
  solarCapacity: number;
  panelCount: number;
  installedSolar: number;
  estimatedDailyGeneration: number;
  monthlyGeneration: number;
  solarCoverage: number;
  inverterRequired: number;
  recommendedInverter: number;
  requiredBatteryKwh: number;
  recommendedBatteryKwh: number;
  backupHours: number;
  estimatedBackupAtCriticalLoad: number;
  averageDailyLoad: number;
};

type SolarReportData = {
  createdAt: string;
  appliances: Appliance[];
  peakSunHours: string;
  panelWattage: string;
  batteryBackupHours: string;
  solarOffset: string;
  results: SolarResults;
};

function numberValue(value: unknown): number {
  const result = Number(value);
  return Number.isFinite(result) ? result : 0;
}

function formatNumber(value: unknown, digits = 2): string {
  return numberValue(value).toFixed(digits);
}

function formatDate(value: string): string {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleString("en-NG", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

export default function SolarReportPage() {
  const [report, setReport] = useState<SolarReportData | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem("samiz_solar_report");

      if (!raw) {
        setError(
          "No Solar Calculator report was found. Please run the Solar Calculator first.",
        );
        return;
      }

      const parsed = JSON.parse(raw) as SolarReportData;

      if (
        !parsed ||
        !parsed.results ||
        !Array.isArray(parsed.appliances)
      ) {
        setError("The saved Solar Calculator report is incomplete.");
        return;
      }

      setReport(parsed);
    } catch {
      setError("Unable to load the Solar Calculator report.");
    }
  }, []);

  const whatsappText = useMemo(() => {
    if (!report) return "";

    const r = report.results;

    const applianceLines = report.appliances
      .map(
        (item) =>
          `• ${item.name}: ${item.quantity} × ${item.watts} W, ${item.hoursPerDay} h/day${item.critical ? ", Critical" : ""}`,
      )
      .join("\n");

    return [
      "SAMIZ TECH ENGINEERING LTD",
      "Solar System Calculation Report",
      "",
      `Daily consumption: ${formatNumber(r.dailyEnergy, 1)} kWh`,
      `Monthly consumption: ${formatNumber(r.monthlyEnergy, 0)} kWh`,
      `Peak load: ${formatNumber(r.peakLoad, 2)} kW`,
      `Recommended solar system: ${formatNumber(r.installedSolar, 2)} kWp`,
      `Solar panels: ${r.panelCount} × ${formatNumber(r.panel, 0)} W`,
      `Recommended inverter: ${formatNumber(r.recommendedInverter, 1)} kVA`,
      `Recommended battery: ${formatNumber(r.recommendedBatteryKwh, 2)} kWh`,
      `Estimated backup: ${formatNumber(r.estimatedBackupAtCriticalLoad, 1)} hours`,
      "",
      "Solar Calculator Inputs",
      `Peak sun hours: ${report.peakSunHours}`,
      `Panel wattage: ${report.panelWattage} W`,
      `Battery backup target: ${report.batteryBackupHours} hours`,
      `Solar target: ${report.solarOffset}%`,
      "",
      "Appliances",
      applianceLines,
      "",
      "Generated by Samiz Tech Energy Tools.",
      "https://www.samiztech.com.ng",
    ].join("\n");
  }, [report]);

  const handleWhatsApp = () => {
    if (!whatsappText) return;

    const url =
      "https://wa.me/?text=" +
      encodeURIComponent(whatsappText);

    window.open(url, "_blank", "noopener,noreferrer");
  };

  const handleExcel = () => {
    if (!report) return;

    const r = report.results;

    downloadReportExcel("Samiz-Solar-Calculation-Report.xlsx", [
      {
        name: "Summary",
        rows: [
          {
            "Report Type": "Solar System Calculation Report",
            "Generated At": formatDate(report.createdAt),
            "Recommended Solar": `${formatNumber(r.installedSolar, 2)} kWp`,
            "Solar Panels": `${r.panelCount} x ${formatNumber(r.panel, 0)} W`,
            "Recommended Inverter": `${formatNumber(r.recommendedInverter, 1)} kVA`,
            "Recommended Battery": `${formatNumber(r.recommendedBatteryKwh, 2)} kWh`,
            "Estimated Backup": `${formatNumber(r.estimatedBackupAtCriticalLoad, 1)} hours`,
          },
        ],
      },
      {
        name: "Solar Inputs",
        rows: [
          {
            "Peak Sun Hours": report.peakSunHours,
            "Panel Wattage (W)": report.panelWattage,
            "Battery Backup Hours": report.batteryBackupHours,
            "Solar Offset (%)": report.solarOffset,
          },
        ],
      },
      {
        name: "Appliances",
        rows: report.appliances.map((item) => ({
          Appliance: item.name,
          Quantity: item.quantity,
          "Power (W)": item.watts,
          "Hours Per Day": item.hoursPerDay,
          Critical: item.critical ? "Yes" : "No",
        })),
      },
      {
        name: "Calculations",
        rows: [
          {
            "Daily Energy (kWh)": r.dailyEnergy,
            "Monthly Energy (kWh)": r.monthlyEnergy,
            "Peak Load (kW)": r.peakLoad,
            "Critical Load (W)": r.criticalLoad,
            "Critical Energy Per Hour (kWh)": r.criticalEnergyPerHour,
            "Sun Hours": r.sunHours,
            "Panel Wattage (W)": r.panel,
            "Solar Offset (%)": r.offset,
            "Solar Capacity (kWp)": r.solarCapacity,
            "Panel Count": r.panelCount,
            "Installed Solar (kWp)": r.installedSolar,
            "Estimated Daily Generation (kWh)": r.estimatedDailyGeneration,
            "Monthly Generation (kWh)": r.monthlyGeneration,
            "Solar Coverage (%)": r.solarCoverage,
            "Required Inverter (kVA)": r.inverterRequired,
            "Recommended Inverter (kVA)": r.recommendedInverter,
            "Required Battery (kWh)": r.requiredBatteryKwh,
            "Recommended Battery (kWh)": r.recommendedBatteryKwh,
            "Backup Hours": r.backupHours,
            "Estimated Backup At Critical Load (hours)":
              r.estimatedBackupAtCriticalLoad,
            "Average Daily Load (kW)": r.averageDailyLoad,
          },
        ],
      },
    ]);
  };

  if (error) {
    return (
      <div className="min-h-[70vh] bg-slate-50 px-6 py-16">
        <div className="mx-auto max-w-3xl rounded-3xl border border-red-200 bg-white p-8 shadow-sm">
          <p className="text-xs font-black uppercase tracking-widest text-red-600">
            Solar Report
          </p>

          <h1 className="mt-3 text-3xl font-black text-slate-950">
            Report unavailable
          </h1>

          <p className="mt-4 text-slate-600">
            {error}
          </p>

          <a
            href="/energy-tools/solar"
            className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white"
          >
            Return to Solar Calculator
          </a>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-[70vh] bg-slate-50 px-6 py-16">
        <div className="mx-auto max-w-5xl">
          <p className="text-sm font-bold text-slate-500">
            Loading Solar Calculation Report...
          </p>
        </div>
      </div>
    );
  }

  const r = report.results;

  return (
    <div className="min-h-screen bg-slate-50 text-slate-950">
      <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
        <div className="flex flex-col gap-6 border-b border-slate-200 pb-8 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">
              Samiz Tech Energy Tools
            </p>

            <h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">
              Solar System Calculation Report
            </h1>

            <p className="mt-3 text-sm text-slate-600">
              Generated {formatDate(report.createdAt)}
            </p>
          </div>

          <div className="flex flex-wrap gap-3 print:hidden">
            <button
              type="button"
              onClick={() => window.print()}
              className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-black text-slate-900"
            >
              Print
            </button>

            <button
              type="button"
              onClick={handleExcel}
              className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-black text-slate-900"
            >
              Download Excel
            </button>

            <button
              type="button"
              onClick={handleWhatsApp}
              className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white"
            >
              Share via WhatsApp
            </button>
          </div>
        </div>

        <section className="mt-8 rounded-3xl bg-slate-950 p-6 text-white sm:p-8">
          <p className="text-xs font-black uppercase tracking-widest text-blue-300">
            Recommended system
          </p>

          <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <p className="text-xs text-slate-400">
                Solar capacity
              </p>
              <p className="mt-1 text-3xl font-black">
                {formatNumber(r.installedSolar, 2)} kWp
              </p>
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Solar panels
              </p>
              <p className="mt-1 text-3xl font-black">
                {r.panelCount} × {formatNumber(r.panel, 0)} W
              </p>
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Inverter
              </p>
              <p className="mt-1 text-3xl font-black">
                {formatNumber(r.recommendedInverter, 1)} kVA
              </p>
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Battery
              </p>
              <p className="mt-1 text-3xl font-black">
                {formatNumber(r.recommendedBatteryKwh, 2)} kWh
              </p>
            </div>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-black">
            Energy summary
          </h2>

          <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {[
              ["Daily consumption", `${formatNumber(r.dailyEnergy, 1)} kWh`],
              ["Monthly consumption", `${formatNumber(r.monthlyEnergy, 0)} kWh`],
              ["Peak load", `${formatNumber(r.peakLoad, 2)} kW`],
              ["Critical load", `${formatNumber(r.criticalLoad / 1000, 2)} kW`],
              ["Solar coverage", `${formatNumber(Math.min(100, r.solarCoverage), 1)}%`],
              ["Daily generation", `${formatNumber(r.estimatedDailyGeneration, 1)} kWh`],
              ["Monthly generation", `${formatNumber(r.monthlyGeneration, 0)} kWh`],
              ["Estimated backup", `${formatNumber(r.estimatedBackupAtCriticalLoad, 1)} hours`],
            ].map(([label, value]) => (
              <div
                key={label}
                className="rounded-2xl border border-slate-200 bg-white p-5"
              >
                <p className="text-xs font-black uppercase tracking-wider text-slate-500">
                  {label}
                </p>
                <p className="mt-2 text-2xl font-black">
                  {value}
                </p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-black">
            Solar Calculator inputs
          </h2>

          <div className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white">
            <div className="grid gap-px bg-slate-200 sm:grid-cols-2">
              {[
                ["Peak sun hours", `${report.peakSunHours} hours`],
                ["Panel wattage", `${report.panelWattage} W`],
                ["Battery backup target", `${report.batteryBackupHours} hours`],
                ["Solar target / offset", `${report.solarOffset}%`],
              ].map(([label, value]) => (
                <div key={label} className="bg-white p-5">
                  <p className="text-xs font-black uppercase tracking-wider text-slate-500">
                    {label}
                  </p>
                  <p className="mt-2 text-lg font-black">
                    {value}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-black">
            Appliance load
          </h2>

          <div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white">
            <table className="w-full min-w-[720px] text-left text-sm">
              <thead className="bg-slate-950 text-white">
                <tr>
                  <th className="px-4 py-3">Appliance</th>
                  <th className="px-4 py-3">Quantity</th>
                  <th className="px-4 py-3">Watts</th>
                  <th className="px-4 py-3">Hours/day</th>
                  <th className="px-4 py-3">Critical</th>
                </tr>
              </thead>

              <tbody>
                {report.appliances.map((item, index) => (
                  <tr
                    key={item.id ?? `${item.name}-${index}`}
                    className="border-t border-slate-200"
                  >
                    <td className="px-4 py-3 font-bold">
                      {item.name}
                    </td>
                    <td className="px-4 py-3">
                      {item.quantity}
                    </td>
                    <td className="px-4 py-3">
                      {item.watts} W
                    </td>
                    <td className="px-4 py-3">
                      {item.hoursPerDay}
                    </td>
                    <td className="px-4 py-3">
                      {item.critical ? "Yes" : "No"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-black">
            Complete calculation results
          </h2>

          <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {[
              ["Daily energy", `${formatNumber(r.dailyEnergy, 2)} kWh`],
              ["Monthly energy", `${formatNumber(r.monthlyEnergy, 2)} kWh`],
              ["Peak load", `${formatNumber(r.peakLoad, 2)} kW`],
              ["Critical load", `${formatNumber(r.criticalLoad, 0)} W`],
              ["Critical energy/hour", `${formatNumber(r.criticalEnergyPerHour, 2)} kWh`],
              ["Sun hours", `${formatNumber(r.sunHours, 1)} h`],
              ["Panel", `${formatNumber(r.panel, 0)} W`],
              ["Offset", `${formatNumber(r.offset, 0)}%`],
              ["Solar capacity", `${formatNumber(r.solarCapacity, 2)} kWp`],
              ["Panel count", `${r.panelCount}`],
              ["Installed solar", `${formatNumber(r.installedSolar, 2)} kWp`],
              ["Daily generation", `${formatNumber(r.estimatedDailyGeneration, 2)} kWh`],
              ["Monthly generation", `${formatNumber(r.monthlyGeneration, 2)} kWh`],
              ["Solar coverage", `${formatNumber(Math.min(100, r.solarCoverage), 0)}%`],
              ["Required inverter", `${formatNumber(r.inverterRequired, 2)} kVA`],
              ["Recommended inverter", `${formatNumber(r.recommendedInverter, 1)} kVA`],
              ["Required battery", `${formatNumber(r.requiredBatteryKwh, 2)} kWh`],
              ["Recommended battery", `${formatNumber(r.recommendedBatteryKwh, 2)} kWh`],
              ["Backup hours", `${formatNumber(r.backupHours, 1)} h`],
              ["Estimated backup at critical load", `${formatNumber(r.estimatedBackupAtCriticalLoad, 1)} h`],
              ["Average daily load", `${formatNumber(r.averageDailyLoad, 2)} kW`],
            ].map(([label, value]) => (
              <div
                key={label}
                className="rounded-2xl border border-slate-200 bg-white p-5"
              >
                <p className="text-xs font-black uppercase tracking-wider text-slate-500">
                  {label}
                </p>
                <p className="mt-2 text-lg font-black">
                  {value}
                </p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-10 rounded-2xl border border-blue-100 bg-blue-50 p-6">
          <p className="text-sm font-bold leading-6 text-slate-700">
            This report reproduces the values calculated by the
            Samiz Tech Solar Calculator using the inputs recorded
            above. Final system design should be validated against
            site conditions, equipment specifications, installation
            standards and applicable engineering requirements.
          </p>
        </section>

        <footer className="mt-10 border-t border-slate-200 pt-6 text-sm text-slate-500">
          Samiz Tech Engineering Ltd — Where Engineering Meets Energy
        </footer>
      </main>

      <style jsx global>{`
        @media print {
          .print\\:hidden {
            display: none !important;
          }

          body {
            background: white !important;
          }

          main {
            max-width: none !important;
          }
        }
      `}</style>
    </div>
  );
}
